apiVersion: v1
kind: ConfigMap
metadata:
  name: h-sepp-config
  namespace: open5gs
data:
  sepp.yaml: |
    logger:
      file:
        path: /var/log/open5gs/sepp.log

    global:

    sepp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://h-nrf.open5gs.svc.cluster.local:80
      n32:
        server:
          - sender: h-sepp.open5gs.svc.cluster.local
        client:
          sepp:
            - receiver: v-sepp.open5gs.svc.cluster.local
              uri: http://v-sepp.open5gs.svc.cluster.local:80
            # --- NEW IPX HOPS ---
            - receiver: v-ipx.open5gs.svc.cluster.local
              uri: tcp://v-ipx.open5gs.svc.cluster.local:6633
            - receiver: h-ipx.open5gs.svc.cluster.local
              uri: tcp://h-ipx.open5gs.svc.cluster.local:6633
            # --- END IPX HOPS ---
            - receiver: h-sepp.open5gs.svc.cluster.local
              uri: http://h-sepp.open5gs.svc.cluster.local:80