apiVersion: v1
kind: ConfigMap
metadata:
  name: h-ipx-sepp-config
  namespace: open5gs
data:
  sepp.yaml: |
    logger:
      file:
        path: /var/log/open5gs/sepp.log
    global:
    sepp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://h-nrf.open5gs.svc.cluster.local:80
      n32:
        server:
          - sender: h-ipx.open5gs.svc.cluster.local
        client:
          sepp:
            - receiver: v-ipx.open5gs.svc.cluster.local
              uri: http://v-ipx.open5gs.svc.cluster.local:80
            - receiver: v-sepp.open5gs.svc.cluster.local
              uri: http://v-sepp.open5gs.svc.cluster.local:80
            - receiver: h-sepp.open5gs.svc.cluster.local
              uri: http://h-sepp.open5gs.svc.cluster.local:80